Repository A-BMT02/snippets, pull requests merged in 2022-10, with the labels that each got.

#8 Updated Readme.md
  README.md
  images/save-it.png
Labels: enhancement

#11 Added functionality to Explore button
  components/nav.js
  pages/index.js
Labels: enhancement

#12 Fix Logo and Explore button
  components/nav.js
  components/sidebar.js
  pages/browse.js
  pages/index.js
Labels: bug

#17 button border fix
  pages/index.js
Labels: bug

#25 Corrected misspelling in README
  README.md
Labels: documentation

#26 add nav-bar hover color
  Context/dataContext.js
  components/nav.js
  components/sidebar.js
  helper/navigations.js
Labels: enhancement
